
/*
 * *********** WARNING **************
 * This file generated by Embperl::WrapXS/0.01
 * Any changes made here will be lost
 * ***********************************
 * 1. /opt/perlt5.6.1/lib/site_perl/5.6.1/ExtUtils/XSBuilder/WrapXS.pm:38
 * 2. /opt/perlt5.6.1/lib/site_perl/5.6.1/ExtUtils/XSBuilder/WrapXS.pm:1883
 * 3. xsbuilder/xs_generate.pl:6
 */


#ifndef EP_XS_TYPEDEFS_H
#define EP_XS_TYPEDEFS_H

typedef tThreadData * Embperl__Thread;
typedef tApp * Embperl__App;
typedef tAppConfig * Embperl__App__Config;
typedef tReq * Embperl__Req;
typedef tReqConfig * Embperl__Req__Config;
typedef tReqParam * Embperl__Req__Param;
typedef tComponent * Embperl__Component;
typedef tComponentConfig * Embperl__Component__Config;
typedef tComponentParam * Embperl__Component__Param;
typedef tComponentOutput * Embperl__Component__Output;
typedef tCacheItem * Embperl__CacheItem;
typedef tTokenTable * Embperl__Syntax;
typedef request_rec * Apache;
typedef server_rec * Apache__Server;
typedef void * PTR;

#ifndef pTHX_
#define pTHX_
#endif
#ifndef aTHX_
#define aTHX_
#endif
#ifndef pTHX
#define pTHX
#endif
#ifndef aTHX
#define aTHX
#endif


#endif /* EP_XS_TYPEDEFS_H */
